[package]
name = "dmitri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
breadx = "2.0.0"
gluten-keyboard = "0.1.2"
# x11rb = "0.9.0"
rusttype = "0.9.2"
font-kit = "0.10.1"
getopts = "0.2"
