[package]
name = "dmitri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
breadx = "2.0.0"
gluten-keyboard = "0.1.2"
rusttype = "0.9.2"
font-loader = "0.11.0"
getopts = "0.2"
rs-complete = "1.3.0"
